/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.avans.ivh5.client.view.ui;

import edu.avans.ivh5.client.control.TreatmentAndSessionController;
import edu.avans.ivh5.shared.model.domain.Employee;
import edu.avans.ivh5.shared.model.domain.Session;
import edu.avans.ivh5.shared.model.domain.Treatment;
import edu.avans.ivh5.shared.model.domain.TreatmentType;
import edu.avans.ivh5.shared.models.ClientDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ferdinand
 */
public class AddSessionScreen extends javax.swing.JFrame {
    private TreatmentAndSessionController controller;
    private boolean newTreatment;
    public int amountOfSessions;
    private Employee therapist;
    private Treatment treatment;
    private ClientDTO client;


    /**
     * Creates new form AddTreatmentScreen2
     */
    public AddSessionScreen(TreatmentAndSessionController treatmentAndSessionController, boolean newTreatment) {
            this.controller = treatmentAndSessionController;
        
            this.amountOfSessions = 0;
            this.newTreatment = newTreatment;
            
            initComponents();
           controller.setUIRef(this);
           fillTherapistComboBox();
           fillTreatmentCodeComboBox();
           if(newTreatment){
               saveButton.setActionCommand("saveTreatment");
               this.therapist = null;
               this.treatment = null;
               this.client = null;
           }
           else{
               saveButton.setActionCommand("alterTreatment");
           }

           saveButton.addActionListener( controller );
           clientSearchField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.getClient(clientSearchField.getText());
            }
           });
           
           if(!newTreatment){
               clientSearchField.setEditable(false);
           }
    }
    
     public AddSessionScreen(TreatmentAndSessionController treatmentAndSessionController, boolean newTreatment, Employee therapist, Treatment treatment, ClientDTO client) {
            this.controller = treatmentAndSessionController;
        
            this.amountOfSessions = 0;
            this.newTreatment = newTreatment;
            
            initComponents();
           controller.setUIRef(this);
           fillTherapistComboBox();
           fillTreatmentCodeComboBox();
           
            this.therapist = therapist;
            this.treatment = treatment;
            this.client = client;
            
           if(newTreatment){
               saveButton.setActionCommand("saveTreatment");
           }
           else{
               saveButton.setActionCommand("alterTreatment");
               this.amountOfSessions = treatment.getSessions().size();
           }

           saveButton.addActionListener( controller );
           clientSearchField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.getClient(clientSearchField.getText());
            }
           });
           
           if(!newTreatment){
               clientSearchField.setEditable(false);
           }
    }
     
     public void updateClient(ClientDTO client){
         this.client = client;
         this.setClientFields();
     }
     
     public void syncTreatmentData(){
         
     }
     
     public void collectSessionData(){
         for(int i = 0; i >= this.amountOfSessions; i++){
             String treatmentCode = sessionsTable.getValueAt(i, 1).toString();
             String date = sessionsTable.getValueAt(i, 2).toString();
             String begin = sessionsTable.getValueAt(i, 3).toString();
             String end = sessionsTable.getValueAt(i, 4).toString();
             this.treatment.addSession(new Session(treatmentCode, date, begin, end, Integer.toString(treatment.getTreatmentID())));
         }
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        therapistComboBox = new javax.swing.JComboBox();
        idLabel = new javax.swing.JLabel();
        firstnameLabel1 = new javax.swing.JLabel();
        lastnameLabel1 = new javax.swing.JLabel();
        telLabel1 = new javax.swing.JLabel();
        mailLabel1 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        firstnameTextField1 = new javax.swing.JTextField();
        lastnameTextField1 = new javax.swing.JTextField();
        telTextField = new javax.swing.JTextField();
        mailTextField1 = new javax.swing.JTextField();
        bsnLabel = new javax.swing.JLabel();
        firstnameLabel2 = new javax.swing.JLabel();
        lastnameLabel2 = new javax.swing.JLabel();
        telLabel = new javax.swing.JLabel();
        mailLabel = new javax.swing.JLabel();
        bsnTextField = new javax.swing.JTextField();
        firstnameTextField2 = new javax.swing.JTextField();
        lastnameTextField2 = new javax.swing.JTextField();
        telTextField2 = new javax.swing.JTextField();
        mailTextField2 = new javax.swing.JTextField();
        therapeutLabel = new javax.swing.JLabel();
        klantLabel = new javax.swing.JLabel();
        treatmentcodeLabel = new javax.swing.JLabel();
        treatmentcodeComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentsTextArea = new javax.swing.JTextArea();
        sessionLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sessionsTable = new javax.swing.JTable();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        clientSearchField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        therapistComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        therapistComboBox.setName(""); // NOI18N

        idLabel.setText("ID");

        firstnameLabel1.setText("Voornaam");

        lastnameLabel1.setText("Achternaam");

        telLabel1.setText("Tel");

        mailLabel1.setText("Mail");

        bsnLabel.setText("BSN");

        firstnameLabel2.setText("Voornaam");

        lastnameLabel2.setText("Achternaam");

        telLabel.setText("Tel");

        mailLabel.setText("Mail");

        bsnTextField.setEditable(false);

        firstnameTextField2.setEditable(false);

        lastnameTextField2.setEditable(false);

        telTextField2.setEditable(false);

        mailTextField2.setEditable(false);

        therapeutLabel.setText("Fysiotherapeut");

        klantLabel.setText("Zoek klant");

        treatmentcodeLabel.setText("Behandelcode:");

        treatmentcodeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        treatmentcodeComboBox.setName(""); // NOI18N

        commentsTextArea.setColumns(20);
        commentsTextArea.setRows(5);
        commentsTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Opmerkingen"));
        jScrollPane1.setViewportView(commentsTextArea);

        sessionLabel.setText("Sessies");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("-");

        jButton2.setBackground(new java.awt.Color(0, 204, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        sessionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "behandelcode", "Datum", "Begintijd", "eindtijd"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(sessionsTable);

        cancelButton.setText("Annuleren");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Opslaan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(therapeutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(therapistComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(134, 134, 134)
                .addComponent(klantLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(treatmentcodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lastnameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(mailLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(telLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(firstnameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(idTextField)
                                            .addComponent(firstnameTextField1)
                                            .addComponent(lastnameTextField1)
                                            .addComponent(telTextField)
                                            .addComponent(mailTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(treatmentcodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(clientSearchField)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(bsnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lastnameLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(telLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(firstnameLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(mailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(bsnTextField)
                                                    .addComponent(firstnameTextField2)
                                                    .addComponent(lastnameTextField2)
                                                    .addComponent(telTextField2)
                                                    .addComponent(mailTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sessionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(123, 123, 123)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(therapeutLabel)
                    .addComponent(klantLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(therapistComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(clientSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(idLabel)
                                                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(bsnLabel)
                                                    .addComponent(bsnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(firstnameLabel1))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(firstnameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(firstnameLabel2)
                                                .addComponent(firstnameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lastnameLabel1))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lastnameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lastnameLabel2)
                                        .addComponent(lastnameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telLabel1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(telTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telLabel)
                                .addComponent(telTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mailLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mailLabel)
                        .addComponent(mailTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(treatmentcodeLabel)
                    .addComponent(treatmentcodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sessionLabel)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        String treatmentCode = String.valueOf(treatmentcodeComboBox.getSelectedItem());
        
        if(this.amountOfSessions == 0){
            //set TreatmentcODE
                sessionsTable.setValueAt(treatmentCode, 0, 0);
             
                //set date of tomorrow
                Date now = new Date();
                Calendar cal = Calendar.getInstance();
                cal.setTime(now);
                cal.add(Calendar.DAY_OF_YEAR, 1); // <--
                Date tomorrow = cal.getTime();
                sessionsTable.setValueAt(tomorrow, 0, 1);

                
                sessionsTable.setValueAt("12:00", 0, 2);
                sessionsTable.setValueAt("12:00", 0, 3);
        }
        else{
                //set TreatmentcODE
                sessionsTable.setValueAt(treatmentCode, this.amountOfSessions, 0);
             
                //set date of tomorrow
                Date now = new Date();
                Calendar cal = Calendar.getInstance();
                cal.setTime(now);
                cal.add(Calendar.DAY_OF_YEAR, 1); // <--
                Date tomorrow = cal.getTime();
                sessionsTable.setValueAt(tomorrow, this.amountOfSessions, 1);

                
                sessionsTable.setValueAt("12:00", this.amountOfSessions, 2);
                sessionsTable.setValueAt("12:00", this.amountOfSessions, 3);
        }
        this.amountOfSessions++;
        /*
        for (int rowIndex=0; rowIndex <= sessionsTable.getRowCount(); rowIndex++){
            Object val = (Object)sessionsTable.getValueAt(rowIndex, 0);
            System.out.println(sessionsTable.getRowCount());
            if(  val != " " ) // just check the first val in JTable.
            {
                //set TreatmentcODE
                sessionsTable.setValueAt(treatmentCode, rowIndex, 0);
             
                //set date of tomorrow
                Date now = new Date();
                Calendar cal = Calendar.getInstance();
                cal.setTime(now);
                cal.add(Calendar.DAY_OF_YEAR, 1); // <--
                Date tomorrow = cal.getTime();
                sessionsTable.setValueAt(tomorrow, rowIndex, 1);

                
                sessionsTable.setValueAt("12:00", rowIndex, 2);
                sessionsTable.setValueAt("12:00", rowIndex, 3);
                rowIndex = sessionsTable.getRowCount();
            }
        }*/
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bsnLabel;
    private javax.swing.JTextField bsnTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField clientSearchField;
    private javax.swing.JTextArea commentsTextArea;
    private javax.swing.JLabel firstnameLabel1;
    private javax.swing.JLabel firstnameLabel2;
    private javax.swing.JTextField firstnameTextField1;
    private javax.swing.JTextField firstnameTextField2;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel klantLabel;
    private javax.swing.JLabel lastnameLabel1;
    private javax.swing.JLabel lastnameLabel2;
    private javax.swing.JTextField lastnameTextField1;
    private javax.swing.JTextField lastnameTextField2;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JLabel mailLabel1;
    private javax.swing.JTextField mailTextField1;
    private javax.swing.JTextField mailTextField2;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel sessionLabel;
    private javax.swing.JTable sessionsTable;
    private javax.swing.JLabel telLabel;
    private javax.swing.JLabel telLabel1;
    private javax.swing.JTextField telTextField;
    private javax.swing.JTextField telTextField2;
    private javax.swing.JLabel therapeutLabel;
    private javax.swing.JComboBox therapistComboBox;
    private javax.swing.JComboBox treatmentcodeComboBox;
    private javax.swing.JLabel treatmentcodeLabel;
    // End of variables declaration//GEN-END:variables

public void fillTherapistComboBox(){
            therapistComboBox.setModel(new DefaultComboBoxModel());
            for (Object item : controller.getEmployees())
                therapistComboBox.addItem(item); 
}

public void fillTreatmentCodeComboBox(){
    treatmentcodeComboBox.setModel(new DefaultComboBoxModel());
    for (Object item: controller.getTreatmentTypes()){
        
        treatmentcodeComboBox.addItem(item);
    }
}

public Treatment saveTreatment(){
        int treatmentID = 0;
        String treatmentCode = (String) treatmentcodeComboBox.getSelectedItem();
        String BSN = bsnTextField.getText();
        String PhysioTherapistLastName = lastnameTextField1.getText();
        String Status = "actief";
        
        Treatment newTreatment = new Treatment(treatmentID, treatmentCode, BSN, PhysioTherapistLastName, Status);
        System.out.println("reached return");
        return newTreatment;
    }


    public void fillFields(){
        if(treatment != null){
            idTextField.setText(Integer.toString(treatment.getTreatmentID()));
        }else{
            idTextField.setText("0");
        }

        if(therapist != null){
            this.setTherapistFields();
        }
        if(client != null){
            this.setClientFields();
        }
    }

    public void setTherapistFields(){
        firstnameTextField1.setText(therapist.getFirstname());
        lastnameTextField1.setText(therapist.getLastname());
        telTextField.setText(therapist.getPhoneNr());
        mailTextField1.setText(therapist.getEmail());
    }

    public void setClientFields(){
        firstnameTextField2.setText(client.getName());
        lastnameTextField2.setText(client.getLastName());
        telTextField2.setText(client.getPhoneNumber());
        mailTextField2.setText(client.getEmailAdress());
        bsnTextField.setText(client.getBSN());
    }
    
    public ClientDTO getClient(){
        return new ClientDTO(firstnameTextField2.getText(), lastnameTextField2.getText(), bsnTextField.getText(), mailTextField2.getText(), telTextField2.getText());
    }
    
    public Employee getTherapist(){
        return new Employee(
                firstnameTextField1.getText(),
                lastnameTextField1.getText(),
                telTextField.getText(),
                mailTextField1.getText()
        );
    }
    

/*
public Treatment saveNewTreatment(){
        int treatmentID = 0;
        String treatmentCode = (String) treatmentcodeComboBox.getSelectedItem();
        String BSN = bsnTextField.getText();
        String PhysioTherapistLastName = lastnameTextField1.getText();
        String Status = "actief";
        
        Treatment newTreatment = new Treatment(treatmentID, treatmentCode, BSN, PhysioTherapistLastName, Status);
        System.out.println("reached return");
        return newTreatment;
    }
*/
}


